### ISSUE TITLE
Lime Green Tea grants berserking instead of vitality

### ISSUE THREAD

**Issue by WaterOre** [brnbrd/VeggieDelight#11]
**Describe the bug**: Lime green tea grants one minute of berserking instead of one minute of vitality
**To Reproduce**: Run collector's reap, respiteful, farmer's delight, farmer's respite, blueprint, neapolitan, and a mod such as JEED or Fermion that reveals food effects

**Expected behavior**: Corrosion (1:00), Vitality (1:00)

**Screenshots**: 
![image](https://user-images.githubusercontent.com/46122502/229697600-08a55524-c252-4118-80e8-ec14d61c82b7.png)

**Versions**: Latest of collector's reap and farmer's delight, 42.3.0 forge

**Comment by brnbrd** [comment]
Fixed in 1.2.2
