### ISSUE TITLE
Harvest With Ease causes limes to not drop

### ISSUE THREAD

**Issue by valchiara** [brnbrd/VeggieDelight#21]
**Describe the bug**: When Harvest With Ease is installed, lime bushes do not drop limes when right clicked, but reverts to 0% growth.

**To Reproduce**: Install Collector's Reap and Harvest With Ease, right click a lime bush with mature limes.

**Expected behavior**: Right clicking lime bush should drop limes.

**Screenshots**: -

**Versions**: Collector's Reap 1.2.4, Harvest With Ease 8.0.1.0

**Comment by brnbrd** [comment]
Can confirm this issue, however it can be circumvented by sneaking. Will try to research more about why it occurs.

**Comment by brnbrd** [comment]
Fixed in v1.3.2
