### ISSUE TITLE
Broken Gummy Recipes

### ISSUE THREAD

**Issue by bolobread** [brnbrd/VeggieDelight#22]
**Describe the bug**: The tags in the recipes for Pumpkin and Passionfruit Gummies are broken

Due to those mods updating, the tags that the recipes rely on have changed and as a result have broken the recipes in this mod. The `roasted_pumpkin` tag no longer exists and has been replaced with `pumpkin_puree` as an item, no tag and the `passionfruit` tag has been renamed to `passion_fruit` for the tag.

**Comment by brnbrd** [comment]
Fixed in v1.3
