### ISSUE TITLE
Fish do not spawn

### ISSUE THREAD

**Issue by FrogBirdd** [brnbrd/VeggieDelight#24]
With Collectors Reap installed all fish stop spawning, including from vanilla and other mods.

Using the latest versions of CR and FD on forge 47.2.0

**Comment by brnbrd** [comment]
I just installed the same version of forge and can not replicate the issue. Make sure you test on a minimal instance.

**Comment by FrogBirdd** [comment]
Seems to have been cause by my personal datapack paired with this mod, my bad. I'll go ahead and close this
