### ISSUE TITLE
Bushes Not Spawning

### ISSUE THREAD

**Issue by josephgilbert** [brnbrd/VeggieDelight#25]
**Describe the bug**: A clear and concise description of what the bug is.
So, I don't know what the spawn rates are for lime and pomegranate bushes, but I've been to maybe 10 flower forests and only found 1 group of lime bushes, and probably 35 warped forests and have found NO pomegranate bushes at all.  At this point I'm fairly certain they're not supposed to be THIS rare to find.
**To Reproduce**: Steps to reproduce the behavior
Try finding any bushes.  Not really sure how to reproduce this bug.
**Expected behavior**: A clear and concise description of what you expected to happen.
I expected there to be at least 1 group of limes per flower forest and 1 pomegranate bush group per warped forest.
**Screenshots**: If applicable, add screenshots to help explain your problem.

**Versions**: Veggie Delight, Farmer's Delight, and Forge versions.
1.20.1 version of Collector's Reap (1.3), Farmer's Delight 1.2.4, Forge 47.2.1.

**Comment by josephgilbert** [comment]
I should add, I've tried updating Forge to the latest version for 1.20.1 (47.2.32), and have tested this in a minimal environment.  This bug still occurs.

**Comment by MadSciSlack** [comment]
I've never found a pomegranate bush either, and I've had this installed for ages.  Lime bush I've found, but are still extremely rare.

**Comment by brnbrd** [comment]
Fixed in v1.3.1
