### ISSUE TITLE
Most recent 1.20.1 version is listed as compatible with 1.19.2 on Curseforge

### ISSUE THREAD

**Issue by katubug** [brnbrd/VeggieDelight#27]
Not really a bug with the mod, but because the new update is marked as compatible with 1.19.2, it prompts users to update and then prevents the game from loading.

**Comment by TheWackyman** [comment]
i hope this gets fixed soon

**Comment by brisingraerowing** [comment]
This is Curseforge's fault. The file is not marked as 1.19.2 on the website, but the app still shows it as compatible with that version. I suspect CF has some issues with not invalidating caches on the API the app uses (or the app caches things and doesn't invalidate them).

**Comment by MadSciSlack** [comment]
Nobody can update the 1.19 version through the app because of this.  You may just want to do a little update so that CF gets its crap together.

**Comment by brnbrd** [comment]
New version has been uploaded
