### ISSUE TITLE
Stop Marine Creatures From Spawning

### ISSUE THREAD

**Issue by AquaOverNight** [brnbrd/VeggieDelight#28]
**Describe the bug**: A clear and concise description of what the bug is.
Issue:Stop marine creatures from spawning
There is no natural spawned fish like tropical fish, salmons or cods

**To Reproduce**: Steps to reproduce the behavior
1.Find an ocean area
2.Load the area by swimming or flying around(Find none or only small amount of fish)
3.Use the following command:
/tag @e[type=!collectorsreap:clam] list
May show you like 210 entities there.

**Expected behavior**: A clear and concise description of what you expected to happen.
 The over-spawning clams could have reached mob spawning limitation.

**Screenshots**: If applicable, add screenshots to help explain your problem.
![221 entities](https://github.com/brnbrd/CollectorsReap/assets/97346660/1e6e8059-623d-4a4b-9716-e4f6a059c260)

**Versions**: Veggie Delight, Farmer's Delight, and Forge versions.
Forge:47.3
Minecraft:1.20.1
Collector's Reap:collectorsreap-1.20.1-1.3.jar
Farmer's Delight:FarmersDelight-1.20.1-1.2.4.jar

**Comment by brnbrd** [comment]
Spawns have been decreased in v1.3.1
