### ISSUE TITLE
19.2 download

### ISSUE THREAD

**Issue by Lilprinceamir** [brnbrd/VeggieDelight#30]
the 19.2 download link for the newest version of the mod insals the 20.1 file

**Comment by brnbrd** [comment]
There is no 1.19.2 download for the newest version, and I did not label it as such.

**Comment by QianFuv** [comment]
![image](https://github.com/user-attachments/assets/e46254c6-1cde-4468-ba09-746b05f29fec)

**Comment by RyanSalad** [comment]
> @QianFuv 

You should create a new issue because it seems the dev still hasn't caught on to this mistake despite several CurseForge comments over the last 4.5 months
