### ISSUE TITLE
Lime Still not growing

### ISSUE THREAD

**Issue by lotusdrive** [brnbrd/VeggieDelight#31]
It would appear that limes still dont grow to 100% ive even upped my tick speed to 3x speed to make sure it wasnt a time issue

**Plant Lime wait**: Steps to reproduce the behavior

**Grow to full 100%**: A clear and concise description of what you expected to happen.

Latest of Collectors Reap and Farmers Delight                 47.2.0 for Forge

**Comment by brnbrd** [comment]
You are not using a Bee. It is stated in the mod description that Lime Bushes "must be pollinated by a Bee to grow fruit". Please read the mod description fully before reporting a bug. However, I will try to add more in-game JEI descriptions to convey this better.

**Comment by lotusdrive** [comment]
apologies for that im sure these get annoying
