### ISSUE TITLE
Are the aquatic creatures not available in the 1.19 version?

### ISSUE THREAD

**Issue by BlueTangsRock** [brnbrd/VeggieDelight#33]
Greetings, on the mod's Forge page I saw that this mod added various aquatic creatures and had a 1.19.2 version, so I downloaded it. In-game, there seems to be no trace of them in the world or in the creative inventory. I'm quite confused about what's going on, but a part of me feels like the aquatic creatures must be exclusive to the 1.20 versions then, for some reason. There seems to be very little information or mentions about the aquatic creatures on the Forge mod page, so if they are exclusive to certain versions I would hope that the mod page could be updated to provide more information and clarification about them. (Also, hopefully, the aquatic creatures could be brought to the 1.19.2 version too.)

Affected Version:
Minecraft 1.19.2 (forge-43.4.0)

**Comment by brnbrd** [comment]
They were added in version [1.3](https://www.curseforge.com/minecraft/mc-mods/collectors-reap/files/5343747), for 1.20.1
