### ISSUE TITLE
Lasagna

### ISSUE THREAD

**Issue by m0thknight** [brnbrd/VeggieDelight#37]
**Describe the bug**: 
When you eat crab lasagna you do not get a bowl back despite the recipe requiring a bowl

**To Reproduce**: 
Use a cooking pot to make crab lasagna. When you make it you will see it listed as being served on a bowl and requires a bowl to craft. When you eat the lasanga you do not get the bowl back

**Expected behavior**: Expect a bowl to appear in my inventory after eating lasagna

**Versions**: Collector's Reap, Farmer's Delight, and Forge/NeoForge versions.
collectors reap 1.3.3
farmer's delight 1.2.4
forge 47.3.7

**Comment by brnbrd** [comment]
Fixed in v1.3.3
