### ISSUE TITLE
Lime Green Tea and Black Pomegranate Tea do not have recipes

### ISSUE THREAD

**Issue by Maltshakes** [brnbrd/VeggieDelight#39]
**Describe the bug**: I have both Collector's Reap and Farmer's Respite installed. The icons for Lime Green Tea and Black Pomegranate Tea show in JEI, but there is not a recipe for either of them, so they cannot be brewed.

**Versions**: 
Minecraft 1.20.1
Collector's Reap: 1.20.1-1.3.2
Farmer's Respite: 1.20.1-2.1.2
Forge: 47.3.0

**Comment by Not-February** [comment]
This is because Farmer's Respite changed its recipes to use actual output fluids, and Collector's Reap hasn't yet adapted to this change.

**Comment by brnbrd** [comment]
Fixed in v1.3.3
