### ISSUE TITLE
urchin and clam won't disappear and take up the number of Water Ambient

### ISSUE THREAD

**Issue by ssfwuu0721** [brnbrd/VeggieDelight#40]
**Describe the bug**: 
Normal fish will disappear 64 blocks away from the player, but urchin and clam will always exist. They can easily reach the limit of Water Ambient so other fish can't spawn.
<img width="197" alt="屏幕截图 2024-10-19 175124_看图王" src="https://github.com/user-attachments/assets/cd5394ef-ec84-4640-8f56-995167185886">
this area of ocean is full of them (at 130+ blocks high, no fish exists)

**To Reproduce**: 
i use curtain (carpet forge ver) mod to see the Water Ambient amount

**Expected behavior**: 
make them disappear like fish

**Versions**: forge 1.20.1, mod 1.3.2

**Comment by brnbrd** [comment]
Fixed in v1.3.3
